name: plug_notas
description: Pacote Flutter para integração com API PlugNotas (NF-e/NFC-e/NFS-e)
version: 1.0.1
homepage: https://github.com/fisromildojr/plug_notas
repository: https://github.com/fisromildojr/plug_notas
issue_tracker: https://github.com/fisromildojr/plug_notas/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.4.0

  # Serialização e Imutabilidade
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Injeção de Dependência
  get_it: ^8.0.0

  # Utilitários
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^3.0.0
  json_serializable: ^6.7.1

  # Lint
  flutter_lints: ^3.0.1

  # Testing
  mocktail: ^1.0.1
  http_mock_adapter: ^0.6.1
